/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCuentaRouteImport } from './routes/_authenticated.cuenta'
import { Route as AuthenticatedCrearRouteImport } from './routes/_authenticated.crear'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedTiendaIdRouteImport } from './routes/_authenticated.tienda.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCuentaRoute = AuthenticatedCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrearRoute = AuthenticatedCrearRouteImport.update({
  id: '/crear',
  path: '/crear',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTiendaIdRoute = AuthenticatedTiendaIdRouteImport.update({
  id: '/tienda/$id',
  path: '/tienda/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/planes': typeof PlanesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/crear': typeof AuthenticatedCrearRoute
  '/cuenta': typeof AuthenticatedCuentaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/t/$slug': typeof TSlugRoute
  '/tienda/$id': typeof AuthenticatedTiendaIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/planes': typeof PlanesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/crear': typeof AuthenticatedCrearRoute
  '/cuenta': typeof AuthenticatedCuentaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/t/$slug': typeof TSlugRoute
  '/tienda/$id': typeof AuthenticatedTiendaIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/planes': typeof PlanesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/crear': typeof AuthenticatedCrearRoute
  '/_authenticated/cuenta': typeof AuthenticatedCuentaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/t/$slug': typeof TSlugRoute
  '/_authenticated/tienda/$id': typeof AuthenticatedTiendaIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/planes'
    | '/sitemap.xml'
    | '/admin'
    | '/crear'
    | '/cuenta'
    | '/dashboard'
    | '/checkout/return'
    | '/t/$slug'
    | '/tienda/$id'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/planes'
    | '/sitemap.xml'
    | '/admin'
    | '/crear'
    | '/cuenta'
    | '/dashboard'
    | '/checkout/return'
    | '/t/$slug'
    | '/tienda/$id'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/planes'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/crear'
    | '/_authenticated/cuenta'
    | '/_authenticated/dashboard'
    | '/checkout/return'
    | '/t/$slug'
    | '/_authenticated/tienda/$id'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PlanesRoute: typeof PlanesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  TSlugRoute: typeof TSlugRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cuenta': {
      id: '/_authenticated/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof AuthenticatedCuentaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crear': {
      id: '/_authenticated/crear'
      path: '/crear'
      fullPath: '/crear'
      preLoaderRoute: typeof AuthenticatedCrearRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tienda/$id': {
      id: '/_authenticated/tienda/$id'
      path: '/tienda/$id'
      fullPath: '/tienda/$id'
      preLoaderRoute: typeof AuthenticatedTiendaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCrearRoute: typeof AuthenticatedCrearRoute
  AuthenticatedCuentaRoute: typeof AuthenticatedCuentaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTiendaIdRoute: typeof AuthenticatedTiendaIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCrearRoute: AuthenticatedCrearRoute,
  AuthenticatedCuentaRoute: AuthenticatedCuentaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTiendaIdRoute: AuthenticatedTiendaIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PlanesRoute: PlanesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  TSlugRoute: TSlugRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
