/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as DemoProductIdRouteImport } from './routes/demo.$productId'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCuentaRouteImport } from './routes/_authenticated.cuenta'
import { Route as AuthenticatedCrearRouteImport } from './routes/_authenticated.crear'
import { Route as AuthenticatedBienvenidaRouteImport } from './routes/_authenticated.bienvenida'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedTiendaIdRouteImport } from './routes/_authenticated.tienda.$id'
import { Route as AuthenticatedPreparandoIdRouteImport } from './routes/_authenticated.preparando.$id'
import { Route as AuthenticatedGuiaIdRouteImport } from './routes/_authenticated.guia.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicGuiaIdRouteImport } from './routes/api/public/guia/$id'
import { Route as ApiPublicCommerceWorkerRouteImport } from './routes/api/public/commerce/worker'
import { Route as ApiPublicCommerceWebhookProviderRouteImport } from './routes/api/public/commerce/webhook.$provider'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoProductIdRoute = DemoProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => DemoRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCuentaRoute = AuthenticatedCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrearRoute = AuthenticatedCrearRouteImport.update({
  id: '/crear',
  path: '/crear',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBienvenidaRoute = AuthenticatedBienvenidaRouteImport.update({
  id: '/bienvenida',
  path: '/bienvenida',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTiendaIdRoute = AuthenticatedTiendaIdRouteImport.update({
  id: '/tienda/$id',
  path: '/tienda/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPreparandoIdRoute =
  AuthenticatedPreparandoIdRouteImport.update({
    id: '/preparando/$id',
    path: '/preparando/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGuiaIdRoute = AuthenticatedGuiaIdRouteImport.update({
  id: '/guia/$id',
  path: '/guia/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGuiaIdRoute = ApiPublicGuiaIdRouteImport.update({
  id: '/api/public/guia/$id',
  path: '/api/public/guia/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCommerceWorkerRoute = ApiPublicCommerceWorkerRouteImport.update({
  id: '/api/public/commerce/worker',
  path: '/api/public/commerce/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCommerceWebhookProviderRoute =
  ApiPublicCommerceWebhookProviderRouteImport.update({
    id: '/api/public/commerce/webhook/$provider',
    path: '/api/public/commerce/webhook/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRouteWithChildren
  '/planes': typeof PlanesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bienvenida': typeof AuthenticatedBienvenidaRoute
  '/crear': typeof AuthenticatedCrearRoute
  '/cuenta': typeof AuthenticatedCuentaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/demo/$productId': typeof DemoProductIdRoute
  '/t/$slug': typeof TSlugRoute
  '/demo/': typeof DemoIndexRoute
  '/guia/$id': typeof AuthenticatedGuiaIdRoute
  '/preparando/$id': typeof AuthenticatedPreparandoIdRoute
  '/tienda/$id': typeof AuthenticatedTiendaIdRoute
  '/api/public/commerce/worker': typeof ApiPublicCommerceWorkerRoute
  '/api/public/guia/$id': typeof ApiPublicGuiaIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/commerce/webhook/$provider': typeof ApiPublicCommerceWebhookProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/planes': typeof PlanesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bienvenida': typeof AuthenticatedBienvenidaRoute
  '/crear': typeof AuthenticatedCrearRoute
  '/cuenta': typeof AuthenticatedCuentaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/demo/$productId': typeof DemoProductIdRoute
  '/t/$slug': typeof TSlugRoute
  '/demo': typeof DemoIndexRoute
  '/guia/$id': typeof AuthenticatedGuiaIdRoute
  '/preparando/$id': typeof AuthenticatedPreparandoIdRoute
  '/tienda/$id': typeof AuthenticatedTiendaIdRoute
  '/api/public/commerce/worker': typeof ApiPublicCommerceWorkerRoute
  '/api/public/guia/$id': typeof ApiPublicGuiaIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/commerce/webhook/$provider': typeof ApiPublicCommerceWebhookProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRouteWithChildren
  '/planes': typeof PlanesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bienvenida': typeof AuthenticatedBienvenidaRoute
  '/_authenticated/crear': typeof AuthenticatedCrearRoute
  '/_authenticated/cuenta': typeof AuthenticatedCuentaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/demo/$productId': typeof DemoProductIdRoute
  '/t/$slug': typeof TSlugRoute
  '/demo/': typeof DemoIndexRoute
  '/_authenticated/guia/$id': typeof AuthenticatedGuiaIdRoute
  '/_authenticated/preparando/$id': typeof AuthenticatedPreparandoIdRoute
  '/_authenticated/tienda/$id': typeof AuthenticatedTiendaIdRoute
  '/api/public/commerce/worker': typeof ApiPublicCommerceWorkerRoute
  '/api/public/guia/$id': typeof ApiPublicGuiaIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/commerce/webhook/$provider': typeof ApiPublicCommerceWebhookProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo'
    | '/planes'
    | '/sitemap.xml'
    | '/admin'
    | '/bienvenida'
    | '/crear'
    | '/cuenta'
    | '/dashboard'
    | '/checkout/return'
    | '/demo/$productId'
    | '/t/$slug'
    | '/demo/'
    | '/guia/$id'
    | '/preparando/$id'
    | '/tienda/$id'
    | '/api/public/commerce/worker'
    | '/api/public/guia/$id'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/commerce/webhook/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/planes'
    | '/sitemap.xml'
    | '/admin'
    | '/bienvenida'
    | '/crear'
    | '/cuenta'
    | '/dashboard'
    | '/checkout/return'
    | '/demo/$productId'
    | '/t/$slug'
    | '/demo'
    | '/guia/$id'
    | '/preparando/$id'
    | '/tienda/$id'
    | '/api/public/commerce/worker'
    | '/api/public/guia/$id'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/commerce/webhook/$provider'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demo'
    | '/planes'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/bienvenida'
    | '/_authenticated/crear'
    | '/_authenticated/cuenta'
    | '/_authenticated/dashboard'
    | '/checkout/return'
    | '/demo/$productId'
    | '/t/$slug'
    | '/demo/'
    | '/_authenticated/guia/$id'
    | '/_authenticated/preparando/$id'
    | '/_authenticated/tienda/$id'
    | '/api/public/commerce/worker'
    | '/api/public/guia/$id'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/commerce/webhook/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRouteWithChildren
  PlanesRoute: typeof PlanesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  TSlugRoute: typeof TSlugRoute
  ApiPublicCommerceWorkerRoute: typeof ApiPublicCommerceWorkerRoute
  ApiPublicGuiaIdRoute: typeof ApiPublicGuiaIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  ApiPublicCommerceWebhookProviderRoute: typeof ApiPublicCommerceWebhookProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$productId': {
      id: '/demo/$productId'
      path: '/$productId'
      fullPath: '/demo/$productId'
      preLoaderRoute: typeof DemoProductIdRouteImport
      parentRoute: typeof DemoRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cuenta': {
      id: '/_authenticated/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof AuthenticatedCuentaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crear': {
      id: '/_authenticated/crear'
      path: '/crear'
      fullPath: '/crear'
      preLoaderRoute: typeof AuthenticatedCrearRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bienvenida': {
      id: '/_authenticated/bienvenida'
      path: '/bienvenida'
      fullPath: '/bienvenida'
      preLoaderRoute: typeof AuthenticatedBienvenidaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tienda/$id': {
      id: '/_authenticated/tienda/$id'
      path: '/tienda/$id'
      fullPath: '/tienda/$id'
      preLoaderRoute: typeof AuthenticatedTiendaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preparando/$id': {
      id: '/_authenticated/preparando/$id'
      path: '/preparando/$id'
      fullPath: '/preparando/$id'
      preLoaderRoute: typeof AuthenticatedPreparandoIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guia/$id': {
      id: '/_authenticated/guia/$id'
      path: '/guia/$id'
      fullPath: '/guia/$id'
      preLoaderRoute: typeof AuthenticatedGuiaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/guia/$id': {
      id: '/api/public/guia/$id'
      path: '/api/public/guia/$id'
      fullPath: '/api/public/guia/$id'
      preLoaderRoute: typeof ApiPublicGuiaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/commerce/worker': {
      id: '/api/public/commerce/worker'
      path: '/api/public/commerce/worker'
      fullPath: '/api/public/commerce/worker'
      preLoaderRoute: typeof ApiPublicCommerceWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/commerce/webhook/$provider': {
      id: '/api/public/commerce/webhook/$provider'
      path: '/api/public/commerce/webhook/$provider'
      fullPath: '/api/public/commerce/webhook/$provider'
      preLoaderRoute: typeof ApiPublicCommerceWebhookProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBienvenidaRoute: typeof AuthenticatedBienvenidaRoute
  AuthenticatedCrearRoute: typeof AuthenticatedCrearRoute
  AuthenticatedCuentaRoute: typeof AuthenticatedCuentaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGuiaIdRoute: typeof AuthenticatedGuiaIdRoute
  AuthenticatedPreparandoIdRoute: typeof AuthenticatedPreparandoIdRoute
  AuthenticatedTiendaIdRoute: typeof AuthenticatedTiendaIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBienvenidaRoute: AuthenticatedBienvenidaRoute,
  AuthenticatedCrearRoute: AuthenticatedCrearRoute,
  AuthenticatedCuentaRoute: AuthenticatedCuentaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGuiaIdRoute: AuthenticatedGuiaIdRoute,
  AuthenticatedPreparandoIdRoute: AuthenticatedPreparandoIdRoute,
  AuthenticatedTiendaIdRoute: AuthenticatedTiendaIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface DemoRouteChildren {
  DemoProductIdRoute: typeof DemoProductIdRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoProductIdRoute: DemoProductIdRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRouteWithChildren,
  PlanesRoute: PlanesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  TSlugRoute: TSlugRoute,
  ApiPublicCommerceWorkerRoute: ApiPublicCommerceWorkerRoute,
  ApiPublicGuiaIdRoute: ApiPublicGuiaIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  ApiPublicCommerceWebhookProviderRoute: ApiPublicCommerceWebhookProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
